version: '3.8'

services:
  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: final_capstone
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres1
    ports:
      - "5433:5432" # 5433 to avoid conflicts with host postgres server
    volumes:
      - ./java/database:/docker-entrypoint-initdb.d
      - postgres-data:/var/lib/postgresql/data #DB data persisting
    networks:
      - capstone-network
    command: ["sh", "/docker-entrypoint-initdb.d/create.sh"]

  java-springboot:
    build: ./java
    ports:
      - "9000:9000"
    environment:
      - SPRING_BOOT_DEVTOOLS_RESTART_ENABLED=true
      - DB_HOST=db
      - DB_PORT=5432
    networks:
      - capstone-network

  vue-web:
    build:
      context: ./vue
      dockerfile: Dockerfile
    volumes:
      - ./vue:/srv/app
      - vue-node_modules:/srv/app/node_modules
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    init: true
    stop_grace_period: 1s
    networks:
      - capstone-network

volumes:
  postgres-data:
  vue-node_modules:

networks:
  capstone-network:
    driver: bridge
