version: '3.8'

services:
  db:
    build: ./java/database
    ports:
      - "5433:5432" # Port mapping
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - capstone-network
  java-springboot:
    build: ./java
    ports:
      - "9000:9000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
    networks:
      - capstone-network
  vue-web:
    build:
      context: ./vue
      dockerfile: Dockerfile
    volumes:
      - ./vue:/srv/app
      - vue-node_modules:/srv/app/node_modules
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    init: true
    stop_grace_period: 1s
    networks:
      - capstone-network

volumes:
  postgres-data:
  vue-node_modules:

networks:
  capstone-network:
    driver: bridge
